xb-def-template:
  slidingWindowSize: ${XB_DEF_TEMPLATE_SLIDING_WINDOW_SIZE}
  minNumberOfCalls: ${XB_DEF_TEMPLATE_MIN_NUM_CALLS}
  failureRateThreshold: ${XB_DEF_TEMPLATE_FAILURE_RATE_THRESHOLD}
  waitDurationInOpenState: ${XB_DEF_TEMPLATE_WAIT_DURATION_OPEN_STATE}
  numCallHalfOpen: ${XB_DEF_TEMPLATE_NUM_CALL_HALF_OPEN}
  exceptionsToCatch: ${XB_DEF_TEMPLATE_EXCEPTIONS_TO_CATCH}
  fallbackProvider: ${XB_DEF_TEMPLATE_FALLBACK_PROVIDER}
  configProvider: ${XB_DEF_TEMPLATE_CONFIG_PROVIDER}
  slidingWindowType: ${XB_DEF_TEMPLATE_SLIDING_WINDOW_TYPE}
  activeFrom: ${XB_DEF_TEMPLATE_ACTIVE_FROM}
  activeTo: ${XB_DEF_TEMPLATE_ACTIVE_TO}
  activeDays: ${XB_DEF_TEMPLATE_ACTIVE_DAYS}
#xircuitb:
#  myCustomXB:
#    slidingWindowSize:
#    minNumberOfCalls:
#    failureRateThreshold:
#    waitDurationInOpenState:
#    numCallHalfOpen:
#    exceptionsToCatch:
#    fallbackProvider:
#    configProvider:
#    slidingWindowType:
#    activeFrom:
#    activeTo:
#    activeDays:
#    # in case of advanced period configuration (mutual exclusive with activeFrom, activeTo, activeDays)
#    activePeriods:
#      - from: "09:00"
#        to: "18:00"
#        days: [ MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY ]
#      - from: "09:00"
#        to: "13:00"
#        days: [ SATURDAY ]
#
#resilix:
# xircuitb:
#  priority: 1